workshop_index:
    path:     /
    defaults: { _controller: "AppBundle:Workshop:index" }
    methods:  GET

workshop_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Workshop:show" }
    methods:  GET

workshop_new:
    path:     /new
    defaults: { _controller: "AppBundle:Workshop:new" }
    methods:  [GET, POST]

workshop_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Workshop:edit" }
    methods:  [GET, POST]

workshop_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Workshop:delete" }
    methods:  DELETE
