app_workshop:
    resource: "@AppBundle/Resources/config/routing/workshop.yml"
    prefix:   /workshop

app_home:
    path:      /
    defaults:  { _controller: AppBundle:Home:index}

app_workshop_register:
    path:      /register-workshop/{id}
    defaults:  { _controller: AppBundle:Workshop:register}

app_workshop_unregister:
    path:      /unregister-workshop/{id}
    defaults:  { _controller: AppBundle:Workshop:unregister}
